import { AdObject } from "../types/adOrders.type";

const adOrders: AdObject[] = [
    {
        id: 1,
        userName: 'JohnDoe',
        adSize: 'Large',
        datePublished: '2024-01-25',
        adLocation: 'Main Street',
        prize: 500,
        status: 'active',
        handlerAgent: 'director',
    },
    {
        id: 2,
        userName: 'JaneSmith',
        adSize: 'Medium',
        datePublished: '2024-01-26',
        adLocation: 'Downtown Square',
        prize: 300,
        status: 'inactive',
        handlerAgent: 'sales agent',
    },
    {
        id: 3,
        userName: 'AliceJohnson',
        adSize: 'Small',
        datePublished: '2024-01-27',
        adLocation: 'Shopping Mall',
        prize: 200,
        status: 'pending',
        handlerAgent: 'chief graphic artist',
    },
    {
        id: 4,
        userName: 'BobMiller',
        adSize: 'Large',
        datePublished: '2024-01-28',
        adLocation: 'City Park',
        prize: 700,
        status: 'active',
        handlerAgent: 'sub graphic designer',
    },
    {
        id: 5,
        userName: 'EvaBrown',
        adSize: 'Medium',
        datePublished: '2024-01-29',
        adLocation: 'Beachfront',
        prize: 400,
        status: 'inactive',
        handlerAgent: 'sales agent',
    },
    {
        id: 6,
        userName: 'CharlieWilson',
        adSize: 'Small',
        datePublished: '2024-01-30',
        adLocation: 'Tech Park',
        prize: 250,
        status: 'pending',
        handlerAgent: 'chief graphic artist',
    },
    {
        id: 7,
        userName: 'GraceJones',
        adSize: 'Large',
        datePublished: '2024-01-31',
        adLocation: 'Airport',
        prize: 600,
        status: 'active',
        handlerAgent: 'sub graphic designer',
    },
    {
        id: 8,
        userName: 'DavidClark',
        adSize: 'Medium',
        datePublished: '2024-02-01',
        adLocation: 'Cinema Complex',
        prize: 350,
        status: 'inactive',
        handlerAgent: 'director',
    },
    {
        id: 9,
        userName: 'SophieWhite',
        adSize: 'Small',
        datePublished: '2024-02-02',
        adLocation: 'Residential Area',
        prize: 180,
        status: 'pending',
        handlerAgent: 'chief graphic artist',
    },
    {
        id: 10,
        userName: 'TomGreen',
        adSize: 'Large',
        datePublished: '2024-02-03',
        adLocation: 'Sports Stadium',
        prize: 750,
        status: 'active',
        handlerAgent: 'sales agent',
    },
    {
        id: 11,
        userName: 'JohnDoe',
        adSize: 'Large',
        datePublished: '2024-01-25',
        adLocation: 'Main Street',
        prize: 500,
        status: 'active',
        handlerAgent: 'director',
    },
    {
        id: 12,
        userName: 'JaneSmith',
        adSize: 'Medium',
        datePublished: '2024-01-26',
        adLocation: 'Downtown Square',
        prize: 300,
        status: 'inactive',
        handlerAgent: 'sales agent',
    },
    {
        id: 13,
        userName: 'AliceJohnson',
        adSize: 'Small',
        datePublished: '2024-01-27',
        adLocation: 'Shopping Mall',
        prize: 200,
        status: 'pending',
        handlerAgent: 'chief graphic artist',
    },
    {
        id: 14,
        userName: 'BobMiller',
        adSize: 'Large',
        datePublished: '2024-01-28',
        adLocation: 'City Park',
        prize: 700,
        status: 'active',
        handlerAgent: 'sub graphic designer',
    },
    {
        id: 15,
        userName: 'EvaBrown',
        adSize: 'Medium',
        datePublished: '2024-01-29',
        adLocation: 'Beachfront',
        prize: 400,
        status: 'inactive',
        handlerAgent: 'sales agent',
    },
    {
        id: 16,
        userName: 'CharlieWilson',
        adSize: 'Small',
        datePublished: '2024-01-30',
        adLocation: 'Tech Park',
        prize: 250,
        status: 'pending',
        handlerAgent: 'chief graphic artist',
    },
    {
        id: 17,
        userName: 'GraceJones',
        adSize: 'Large',
        datePublished: '2024-01-31',
        adLocation: 'Airport',
        prize: 600,
        status: 'active',
        handlerAgent: 'sub graphic designer',
    },
    {
        id: 18,
        userName: 'DavidClark',
        adSize: 'Medium',
        datePublished: '2024-02-01',
        adLocation: 'Cinema Complex',
        prize: 350,
        status: 'inactive',
        handlerAgent: 'director',
    },
    {
        id: 19,
        userName: 'SophieWhite',
        adSize: 'Small',
        datePublished: '2024-02-02',
        adLocation: 'Residential Area',
        prize: 180,
        status: 'pending',
        handlerAgent: 'chief graphic artist',
    },
    {
        id: 20,
        userName: 'TomGreen',
        adSize: 'Large',
        datePublished: '2024-02-03',
        adLocation: 'Sports Stadium',
        prize: 750,
        status: 'active',
        handlerAgent: 'sales agent',
    },
];

export default adOrders